SOURCES = [
    # TIER 1 — Official Government
    {
        "id": "uscis_policy_manual",
        "name": "USCIS Policy Manual",
        "base_url": "https://www.uscis.gov/policy-manual",
        "source_type": "official",
        "visa_categories": ["H1B", "F1", "B1B2", "L1", "EB1", "EB2", "EB3"],
        "weight": 1.0,
        "crawl_depth": 3,
    },
    {
        "id": "travel_state_gov",
        "name": "travel.state.gov",
        "base_url": "https://travel.state.gov/content/travel/en/us-visas.html",
        "source_type": "official",
        "visa_categories": ["H1B", "F1", "B1B2", "L1", "EB1", "EB2", "EB3"],
        "weight": 1.0,
        "crawl_depth": 2,
    },
    {
        "id": "cbp_gov",
        "name": "CBP.gov",
        "base_url": "https://www.cbp.gov/travel/international-visitors",
        "source_type": "official",
        "visa_categories": ["B1B2", "F1", "H1B", "L1"],
        "weight": 1.0,
        "crawl_depth": 2,
    },
    # TIER 2 — Legal Interpretation
    {
        "id": "murthy_law",
        "name": "Murthy Law Firm",
        "base_url": "https://www.murthy.com/news/",
        "source_type": "legal_interpretation",
        "visa_categories": ["H1B", "F1", "L1", "EB1", "EB2", "EB3"],
        "weight": 0.85,
        "crawl_depth": 2,
    },
    {
        "id": "fragomen",
        "name": "Fragomen Blog",
        "base_url": "https://www.fragomen.com/insights.html",
        "source_type": "legal_interpretation",
        "visa_categories": ["H1B", "L1", "EB1", "EB2", "EB3"],
        "weight": 0.85,
        "crawl_depth": 2,
    },
    {
        "id": "ilw",
        "name": "ILW.com",
        "base_url": "https://www.ilw.com/immigrationdaily/news/",
        "source_type": "legal_interpretation",
        "visa_categories": ["H1B", "F1", "B1B2", "L1", "EB1", "EB2", "EB3"],
        "weight": 0.8,
        "crawl_depth": 1,
    },
    {
        "id": "aila",
        "name": "AILA Practice Advisories",
        "base_url": "https://www.aila.org/advo-media/aila-practice-pointers-and-advisories",
        "source_type": "legal_interpretation",
        "visa_categories": ["H1B", "F1", "L1", "EB1", "EB2", "EB3"],
        "weight": 0.9,
        "crawl_depth": 1,
    },
    {
        "id": "nolo",
        "name": "Nolo Immigration Guides",
        "base_url": "https://www.nolo.com/legal-encyclopedia/immigration",
        "source_type": "legal_interpretation",
        "visa_categories": ["H1B", "F1", "B1B2", "L1", "EB1", "EB2", "EB3"],
        "weight": 0.75,
        "crawl_depth": 2,
    },
    # TIER 3 — News / Think Tanks
    {
        "id": "mpi",
        "name": "Migration Policy Institute",
        "base_url": "https://www.migrationpolicy.org/topics/us-immigration-policy",
        "source_type": "news",
        "visa_categories": ["H1B", "F1", "B1B2", "L1", "EB1", "EB2", "EB3"],
        "weight": 0.8,
        "crawl_depth": 1,
    },
    {
        "id": "aic",
        "name": "American Immigration Council",
        "base_url": "https://www.americanimmigrationcouncil.org/research",
        "source_type": "news",
        "visa_categories": ["H1B", "F1", "B1B2", "L1", "EB1", "EB2", "EB3"],
        "weight": 0.7,
        "crawl_depth": 1,
    },
    # TIER 4 — Community (low weight, anecdotal)
    {
        "id": "trackitt",
        "name": "Trackitt.com",
        "base_url": "https://www.trackitt.com",
        "source_type": "community",
        "visa_categories": ["H1B", "F1", "B1B2", "L1", "EB1", "EB2", "EB3"],
        "weight": 0.3,
        "crawl_depth": 1,
    },
    {
        "id": "visajourney",
        "name": "VisaJourney",
        "base_url": "https://www.visajourney.com",
        "source_type": "community",
        "visa_categories": ["B1B2", "F1", "EB1", "EB2", "EB3"],
        "weight": 0.3,
        "crawl_depth": 1,
    },
]

LIVE_SEARCH_DOMAINS = [
    "uscis.gov",
    "travel.state.gov",
    "murthy.com",
    "fragomen.com",
    "ilw.com",
    "aila.org",
    "migrationpolicy.org",
]
