"""Turning tool activity into a line the user can read while they wait.

The chat UI shows a status line while a turn is in flight, the way a person
says "hang on, looking that up" instead of going quiet. Labels are built from
what the agent is actually doing, not from a fixed string per tool: the model's
own tool arguments carry the subject of the lookup, so the status can say
"checking official guidance on the H-1B grace period" rather than "working".

Deliberately NOT generated by a model. An extra inference call to describe the
work would add latency to the thing that exists to cover latency, and it would
be the one part of the turn that could hallucinate about itself.

What a label never contains: a tool name, a provider, a domain, a raw URL.
Those are implementation details, and a status line that leaks them reads as
debug output rather than as reassurance.
"""

from __future__ import annotations

import re

#: What each tool looks like from outside, as a verb phrase the subject can be
#: appended to. Anything unmapped falls back to the generic form rather than
#: exposing a function name.
TOOL_VERBS = {
    "search_official_guidance": "Checking official guidance",
    "search_community_experiences": "Looking for people's experiences",
    "lookup_regulation": "Reading the regulation",
    "search_recent_developments": "Checking recent developments",
}

DEFAULT_VERB = "Working on it"

#: Said instead of repeating the subject when the model goes back for more.
#: Round two looking identical to round one is what makes a UI read as frozen.
FOLLOW_UP_VERBS = {
    "search_official_guidance": "Still checking — one more source",
    "search_community_experiences": "Still reading what people reported",
    "search_recent_developments": "Still checking for updates",
}

DEFAULT_FOLLOW_UP = "Still working on it"

#: Long enough to identify the subject, short enough for one line on a phone.
MAX_SUBJECT_CHARS = 52

#: Search queries carry operators and hints meant for a provider, not for a
#: person. Stripped so the status reads as English.
_NOISE = re.compile(r"\b(site:\S+|filetype:\S+|AND|OR)\b", re.IGNORECASE)
_PUNCT = re.compile(r"[\"'`*()\[\]{}]")


def summarise_subject(query: str) -> str:
    """Turn a search query into something worth showing a waiting person."""
    text = _PUNCT.sub(" ", _NOISE.sub(" ", query or ""))
    text = " ".join(text.split())
    if not text:
        return ""
    if len(text) <= MAX_SUBJECT_CHARS:
        return text
    # Cut on a word boundary: a label ending mid-word looks like a bug.
    clipped = text[:MAX_SUBJECT_CHARS].rsplit(" ", 1)[0]
    return f"{clipped or text[:MAX_SUBJECT_CHARS]}…"


def build_label(function_name: str, arguments: dict | None, *, round_number: int) -> str:
    """Compose the line the user sees for one tool call."""
    if round_number > 1:
        return FOLLOW_UP_VERBS.get(function_name, DEFAULT_FOLLOW_UP)

    verb = TOOL_VERBS.get(function_name, DEFAULT_VERB)
    subject = summarise_subject(str((arguments or {}).get("query", "")))
    return f"{verb} — {subject}" if subject else verb
